//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace rts_map.Localizations {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocaleStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocaleStrings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("rts_map.Localizations.LocaleStrings", typeof(LocaleStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   English に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string AppLocale {
            get {
                return ResourceManager.GetString("AppLocale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsApiHeader {
            get {
                return ResourceManager.GetString("SettingsApiHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use personal API Key to access real-time data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsApiKeyDescription {
            get {
                return ResourceManager.GetString("SettingsApiKeyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   API Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsApiKeyHeader {
            get {
                return ResourceManager.GetString("SettingsApiKeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The language being displayed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAppLocaleDescription {
            get {
                return ResourceManager.GetString("SettingsAppLocaleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsAppLocaleHeader {
            get {
                return ResourceManager.GetString("SettingsAppLocaleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Wave Charts on the right side of the map. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsChartsEnabledDescription {
            get {
                return ResourceManager.GetString("SettingsChartsEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable Wave Charts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsChartsEnabledHeader {
            get {
                return ResourceManager.GetString("SettingsChartsEnabledHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wave Charts に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsChartsHeader {
            get {
                return ResourceManager.GetString("SettingsChartsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Personalize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeHeader {
            get {
                return ResourceManager.GetString("SettingsThemeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   How the application be colored in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeModeDescription {
            get {
                return ResourceManager.GetString("SettingsThemeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeModeHeader {
            get {
                return ResourceManager.GetString("SettingsThemeModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeModeOptionDark {
            get {
                return ResourceManager.GetString("SettingsThemeModeOptionDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeModeOptionLight {
            get {
                return ResourceManager.GetString("SettingsThemeModeOptionLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Default に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingsThemeModeOptionSystem {
            get {
                return ResourceManager.GetString("SettingsThemeModeOptionSystem", resourceCulture);
            }
        }
    }
}
